### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by zkymx** [maxinjohn/OpenVPN-AS_license_unlocker#1]
I have error:
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing OpenVPN Access Server License Unlocker  100%

Starting install.. if you want to abort install now, then press ctrl+c within 10 seconds...

Nothing pressed, proceeding installation..

Checing Zip/Unzip tools are installed or not.

zip is installed: ok
zip is installed: ok
unzip:  cannot find or open ./Pyovpnc-1.2-py3.12-linux-x86_64.egg, ./Pyovpnc-1.2-py3.12-linux-x86_64.egg.zip or ./Pyovpnc-1.2-py3.12-linux-x86_64.egg.ZIP.
find: ‘./Pyovpnc-1.2-py3.12-linux-x86_64.egg’: No such file or directory
openvpn_as_license_unlocker.sh: line 35: pyovpn/lic/uprop.py: No such file or directory
        zip warning: missing end signature--probably not a zip file (did you
        zip warning: remember to use binary mode when you transferred it?)
        zip warning: (if you are trying to read a damaged archive try -F)

zip error: Zip file structure invalid (/usr/local/openvpn_as/lib/python/Pyovpnc-1.2-py3.12-linux-x86_64.egg)

 OpenVPN license is unloced and service is active.

**Comment by maxinjohn** [comment]
I understand the error &  I never seen such a file called Pyovpnc-1.2-py3.12-linux-x86_64.egg in the openvpn install folder, and pushed fixes ,  and should be ok now , if you face any issues let me know..

**Comment by zkymx** [comment]
it worked!!!
